# language: c++
language: minimal
  
script:
- sudo cat /etc/hosts
- sudo ls

jobs:
  include:
  - dist: xenial
    arch: ppc64le
    #group: edge
    #group: dev
#     script:
#       - /opt/at12.0/bin/g++ hello_world.cpp -o hello_world
#       - ./hello_world
  - dist: bionic
    arch: ppc64le
    #group: edge
    #group: dev
#     script:
#       - /opt/at14.0/bin/g++ hello_world.cpp -o hello_world
#       - ./hello_world
  - dist: focal
    arch: ppc64le
    #group: edge
    #group: dev
#     script:
#       - /opt/at14.0/bin/g++ hello_world.cpp -o hello_world
#       - ./hello_world
